# Generated by Django 4.0.6 on 2022-07-07 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coord_x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coord_y', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('GS', 'Gas'), ('LQ', 'Liquid'), ('CT', 'Container'), ('LS', 'Loose')], max_length=255)),
                ('weight', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TS', 'Tankship'), ('CS', 'Container ship'), ('BC', 'Bulk carrier')], max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('RW', 'Railway'), ('PL', 'Pipeline')], max_length=255)),
                ('node_0', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='land_start_for', to='mainapp.node')),
                ('node_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='land_end_for', to='mainapp.node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeaRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ice_level', models.PositiveSmallIntegerField()),
                ('fullness', models.PositiveSmallIntegerField()),
                ('bandwidth', models.PositiveSmallIntegerField()),
                ('node_0', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sea_start_for', to='mainapp.node')),
                ('node_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sea_end_for', to='mainapp.node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.transportship')),
            ],
        ),
    ]
